
name: test-1

on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'Enter the SNAPSHOT build version'
        required: true

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Define new version
        run: echo "NEW_VERSION=${{ github.event.inputs.snapshot_version }}" >> $GITHUB_ENV

      - name: Update version for swagger-petstore in pom.xml
        run: |
          # Update the version for the swagger-petstore artifact only
          sed -i -E '/<artifactId>swagger-petstore<\/artifactId>/,/<\/version>/ s|<version>[0-9A-Za-z.-]*</version>|<version>'"$NEW_VERSION"'</version>|' pom.xml

      - name: Commit version change
        run: |
          git add pom.xml
          git commit -m "Update version to $NEW_VERSION"
          git push origin master

      - name: Build with Maven
        run: mvn clean install

  # Step 4: Raise a Pull Request after successful build
  raise-pr:
    runs-on: ubuntu-latest
    needs: checkout-and-build
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update version to ${{ env.NEW_VERSION }}"
          body: |
            This PR updates the swagger-petstore version to ${{ env.NEW_VERSION }}.
          base: main
          head: master
          commit-message: "Update version to ${{ env.NEW_VERSION }}"

  # Step 5: CodeQL scanning on PR raise
  codeql-scan:
    runs-on: ubuntu-latest
    needs: raise-pr
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: mvn clean install

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
